# Generated by Django 5.1.3 on 2024-12-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='vote_count',
        ),
    ]
